### ISSUE TITLE
FAIL Installing InfluxDB::LineProtocol failed.

### ISSUE THREAD

**Issue by sdeseille** [domm/InfluxDB-LineProtocol#3]
Hello

I tried to update InfluxDB::LineProtocol to version 1.003 without success.

Here you will see my install log output:

cpanm (App::cpanminus) 1.7027 on perl 5.020002 built for MSWin32-x64-multi-thread
Work directory is D:\strawberry-perl-5.20.2.1-64bit-PDL\data/.cpanm/work/1438531954.5160
You have make D:\strawberry-perl-5.20.2.1-64bit-PDL\c\bin\dmake.exe
You have LWP 6.13
Falling back to Archive::Tar 2.04
Searching InfluxDB::LineProtocol on cpanmetadb ...
--> Working on InfluxDB::LineProtocol
Fetching http://www.cpan.org/authors/id/D/DO/DOMM/InfluxDB-LineProtocol-1.003.tar.gz
-> OK
Unpacking InfluxDB-LineProtocol-1.003.tar.gz
Entering InfluxDB-LineProtocol-1.003
Checking configure dependencies from META.json
Checking if you have Module::Build 0.28 ... Yes (0.4211)
Configuring InfluxDB-LineProtocol-1.003
Running Build.PL
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'InfluxDB-LineProtocol' version '1.003'
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have warnings 0 ... Yes (1.23)
Checking if you have Time::HiRes 0 ... Yes (1.9726)
Checking if you have Test::Most 0 ... Yes (0.34)
Checking if you have Carp 0 ... Yes (1.3301)
Checking if you have Exporter 0 ... Yes (5.71)
Checking if you have Module::Build 0.28 ... Yes (0.4211)
Checking if you have lib 0 ... Yes (0.63)
Checking if you have strict 0 ... Yes (1.08)
Checking if you have Test::More 0 ... Yes (1.001014)
Building and testing InfluxDB-LineProtocol-1.003
Building InfluxDB-LineProtocol
t/00-load.t ... ok
# Failed test 'data2line case 16'
# at t/10_basic.t line 190.
# got: 'metric value=7.51696501241595e-005 1437072205500681000'
# expected: 'metric value=7.51696501241595e-05 1437072205500681000'
# Failed test 'line2data case 16'
# at t/10_basic.t line 192.
# Compared $data->[1]{"value"}
# got : '7.51696501241595e-05'
# expect : '7.51696501241595e-005'
# Looks like you failed 2 tests of 48.

t/10_basic.t .. 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/48 subtests 
    (1 TODO test unexpectedly succeeded)
## Test Summary Report

t/10_basic.t (Wstat: 512 Tests: 48 Failed: 2)
  Failed tests:  33-34
  TODO passed:   37
  Non-zero exit status: 2
Files=2, Tests=49,  1 wallclock secs ( 0.09 usr +  0.05 sys =  0.14 CPU)
Result: FAIL
Failed 1/2 test programs. 2/49 subtests failed.
-> FAIL Installing InfluxDB::LineProtocol failed. See D:\strawberry-perl-5.20.2.1-64bit-PDL\data.cpanm\work\1438531954.5160\build.log for details. Retry with --force to force install it.

Don't hesitate to ask if you want me to test something specific.

Regards

sdeseille

**Comment by pplu** [comment]
Hi!

Looks like it's a bug in the test suite (your perl represents floats with an extra zero in the exponent) . It looks ok to force install. Do you know why your perl adds the extra zero to the exponent?

**Comment by domm** [comment]
Seems to be caused by some differences between strawberry Perl / windows and Linux Perls.
cpantesters reports several success, but all for linux:
http://matrix.cpantesters.org/?dist=InfluxDB-LineProtocol+1.003

Perlmonks has this to say
http://www.perlmonks.org/?node_id=879893

It seems that we should make the test a bit more lax...

**Comment by sdeseille** [comment]
I don't know why perl adds the extra zero to the exponent?

But in the same time there is something disapointing. If you look test 'data2line case 16' Perl add an extra zero to the exponent but if you look test 'line2data case 16' Perl remove a zero to the exponent. 

regards
sdeseille
