### ISSUE TITLE
LineProtocol change for 0.9.3

### ISSUE THREAD

**Issue by pplu** [domm/InfluxDB-LineProtocol#4]
Hi!

  Looks like 0.9.3 has changed the Line Protocol:

  https://github.com/influxdb/influxdb/blob/master/CHANGELOG.md

  "To store data points as integers you must now append i to the number if using the line protocol"

  How would you like to approach this from the client?

**Comment by domm** [comment]
the joys of the bleeding edge :-)

I guess the best idea would be to switch to the new format, but maybe retain the old one via some config option. So we would also introduce a breaking change, but allow users of the old format (for example, the company I wrote this piece of code for :-) to still keep working, without having to update InfluxDB immediately.

I can probably implement this in the next few days. But if you need the new version ASAP, feel free to submit a patch :-)

The easiest (but ugly) way to turn on the "old" integer handling would be to introduce a global value
$InfluxDB::LineProtocol::format, defaulting to 'current'.
For now, the only other value is '0.9.2'. If you do
$InfluxDB::LineProtocol::format = '0.9.2', you should get Intergers without the 'i'.
If there are any further changes to the line protocol, we can add 0.9.3 and so on.

The fastest way to implement the check (avoiding lots if ifs in the code) is to write version-specific date2line/line2date functions (_date2line_0_9_2, _date2line_current), and install the correct one via symbol table munging, based on $InfluxDB::LineProtocol::format.

What do you think about that?

Greetings,
domm

PS: And thanks for keeping an eye on the Changelog! :-)
PPS: Do you want co-maint on github and/or CPAN?

**Comment by pplu** [comment]
No hurry on our side. I thought I would just give you a heads up. 

I'd personally prefer a way to make the configuration non-global. Something like an attribute in the constructor to determine the behaviour. 

I'll back that up with code when I get to it :) 

COMAINT would be OK if you want,  just to have more than one person able to release :)

**Comment by domm** [comment]
Fixed in 1.005:

If you want some old behavior:
  use InfluxDB::LineProtocol qw(v0.9.2 data2line line2data);

This will get you the current version:
  use InfluxDB::LineProtocol qw(data2line line2data);

If there are a lot more similar changes, I will move the legacy code into a separate module..

**Comment by pplu** [comment]
Great!

Will be on 0.9.3 soon :). Ups! :laughing: They've launched 0.9.4 alredy! :laughing: (no changes to line protocol, luckily)
